### ISSUE TITLE
Wondering about dataset update

### ISSUE THREAD

**Issue by SejeongPark8354** [ASKCOS/askcos-core#1]
First of all, Thank you for your wonderful work in CASP area. 
I used askcos based on python using docker.
I wonder that askcos-data in the docker you made is the newest version? (like public release 2020.07)
I'd really appreciate it if you could reply.

**Comment by connorcoley** [comment]
Thanks! Yes, that's the newest version that is publicly available

**Comment by mliu49** [comment]
To add on, if you're using the latest Docker images from Docker Hub (either askcos/askcos-core or askcos/askcos-site), those contain the 2020.07 release of askcos-data. Also, note that the only change in [askcos-data 2020.07](https://github.com/ASKCOS/askcos-data/releases/tag/2020.07) was the addition of a new general selectivity model. The existing models are identical to those in v0.4.1.

**Comment by SejeongPark8354** [comment]
@connorcoley @mliu49 Thank you for your fast responses. Can I ask one more question as the last one? Then, are the buyables and templates uploaded the latest version? I think the version can effect on the results. 
Thank you again!!

**Comment by mliu49** [comment]
It depends on what you mean by latest version. They are the latest version that have we have publicly released, but they would not reflect buyable compounds available today or newly published reactions from the last few years.

You are correct in that the buyables list and templates can have a significant effect on results. You can easily replace the buyables list with your own, which is just a list of RDKit canonicalized SMILES and prices. Templates would be much harder to replace, as you would need to retrain the template relevance model as well. I don't think we have released that retraining code yet, but we do plan to at some point.

**Comment by SejeongPark8354** [comment]
@mliu49 Oh, I mean that  buyable compounds available today or newly published reactions from the last few years. As you mentioned, I will try to update buyables list by my self. Thank you for your kind explanation. I hope you release retraining code soon. :) Thanks, again!
