### ISSUE TITLE
what is the meaning of  output of quantitative condition predictions?

### ISSUE THREAD

**Issue by queliyong** [ASKCOS/askcos-core#7]
Hi, 
I have two questions below:
1.Does the "Reagents" column include catalysts and solvents, or just include reagents?
2.The "(Amount)" beside the "Reagents" means what? mol, ml, or g?
Thank u very much.
![Dingtalk_20221128150202](https://user-images.githubusercontent.com/56716710/206076984-bbb31c73-6eb7-49d6-bcd4-158fc78f5813.jpg)

**Comment by connorcoley** [comment]
These are molar equivalents, normalized to the (predicted) limiting starting material. The "Reagents" column in this output does not distinguish between reagents, catalysts, and solvents as differentiated in other contexts -- you should think of it like "Agents" instead.

**Comment by queliyong** [comment]
> These are molar equivalents, normalized to the (predicted) limiting starting material. The "Reagents" column in this output does not distinguish between reagents, catalysts, and solvents as differentiated in other contexts -- you should think of it like "Agents" instead.

Thanks a lot.
